name: Deploy Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering of the workflow from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment to run MergeDataFiles.py
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install Python dependencies and run the MergeDataFiles.py script
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have any dependencies in requirements.txt, uncomment the next line
        # pip install -r requirements.txt
        python MergeDataFiles/MergeDataFiles.py

    # Copy the generated combined_metadata.json to the StaticSiteGeneration/public directory
    - name: Copy combined_metadata.json to StaticSiteGeneration
      run: |
        cp MergeDataFiles/combined_metadata.json StaticSiteGeneration/public/

    # Set up Node.js environment to run npm commands
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install npm dependencies
    - name: Install npm dependencies
      working-directory: StaticSiteGeneration
      run: npm install

    # Generate the static site
    - name: Generate static site
      working-directory: StaticSiteGeneration
      run: npm run generate

    # Preview the static site (optional, only if needed for local hosting)
    - name: Preview static site
      working-directory: StaticSiteGeneration
      run: npm run preview

    # (Optional) Deploy to GitHub Pages
    # If you want to deploy to GitHub Pages, use the following steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Configure the folder you want to deploy (build output from Nuxt)
        publish_dir: StaticSiteGeneration/.output/public
        # Optionally configure a custom branch for deployment
        # publish_branch: gh-pages
