name: Deploy Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Check out the repository with the RSE content
    - name: Checkout Research Software Ecosystem content repository
      uses: actions/checkout@v4
      with:
        repository: research-software-ecosystem/content
        path: MergeDataFiles/content
        

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Cache Node.js dependencies
    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: StaticSiteGeneration/node_modules
        key: node-modules-${{ hashFiles('StaticSiteGeneration/package-lock.json') }}
        restore-keys: |
          node-modules-

    # Cache Python dependencies
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ hashFiles('MergeDataFiles/requirements.txt') }}
        restore-keys: |
          pip-cache-

    # Cache the content directory and metadata
    # - name: Cache RSE content directory and metadata
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       MergeDataFiles/content
    #       MergeDataFiles/combined_metadata.json
    #     key: content-${{ hashFiles('MergeDataFiles/content/.git/HEAD', 'MergeDataFiles/content/.git/refs/remotes/origin/master', 'MergeDataFiles/combined_metadata.json', 'MergeDataFiles/requirements.txt') }}
    #     restore-keys: |
    #       content-

    # Run Makefile rule: install-all (install Python, Node.js dependencies)
    - name: Install all dependencies (Python and Node.js)
      run: |
        make install-all

    # Run Makefile rule: refresh-metadata (handle cloning or updating of the repository and generating combined metadata JSON file)
    - name: Clone or update RSE content repository
      run: |
        make refresh-metadata

    # Run Makefile rule: copy-metadata (copy metadata to public directory)
    - name: Copy metadata to public directory
      run: |
        make copy-metadata

    # Run Makefile rule: generate-site (generate static site)
    - name: Generate static site
      run: |
        make generate-site

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_dir: StaticSiteGeneration/.output/public
        github_token: ${{ secrets.GITHUB_TOKEN }}
