name: Deploy Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Run Makefile rule: run-python
    - name: Run Python processing
      run: |
        make run-python

    # Run Makefile rule: copy-metadata
    - name: Copy metadata to public directory
      run: |
        make copy-metadata

    # Run Makefile rule: install-node
    - name: Install npm dependencies
      run: |
        make install-node

    # Run Makefile rule: generate-site
    - name: Generate static site
      run: |
        make generate-site

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: StaticSiteGeneration/.output/public
        github_token: ${{ secrets.GITHUB_TOKEN }}
